"""TradeLab's public Python API."""

from . import research
from .data import (
    backtest_historical,
    cached_candles_path,
    candle_stats,
    fetch_historical,
    fetch_latest_candle,
    get_historical_candles,
    load_candles_from_cache,
    load_candles_from_csv,
    merge_candles,
    normalize_candles,
    save_candles_to_cache,
)
from .engine import (
    BarSystemRunner,
    BudgetExceededError,
    LlmSignal,
    backtest,
    backtest_async,
    backtest_portfolio,
    backtest_ticks,
    financing_cost,
    funding_events,
    grid,
    optimize,
    walk_forward_optimize,
    with_budget,
)
from .errors import (
    BrokerError,
    DataProviderError,
    LiveTradingDisabledError,
    RiskRejectedError,
    StrategyError,
    TradeLabError,
    ValidationError,
)
from .metrics import BIG_NUMBER, benchmark_stats, build_metrics, clamp_finite, periods_per_year
from .models import BacktestResult, Candle, Signal, to_primitive
from .reporting import (
    export_backtest_artifacts,
    export_html_report,
    export_metrics_json,
    export_trades_csv,
    render_html_report,
    summarize,
)
from .research import create_research_store
from .strategies import get_strategy, list_strategies, register_strategy
from .utils import (
    atr,
    bps_of,
    calculate_position_size,
    detect_fvg,
    ema,
    in_windows_et,
    is_session,
    last_swing,
    minutes_et,
    offset_et,
    parse_windows_csv,
    pct,
    structure_state,
    swing_high,
    swing_low,
)

__all__ = [
    "BIG_NUMBER",
    "BacktestResult",
    "BarSystemRunner",
    "BrokerError",
    "BudgetExceededError",
    "Candle",
    "DataProviderError",
    "LiveTradingDisabledError",
    "LlmSignal",
    "RiskRejectedError",
    "Signal",
    "StrategyError",
    "TradeLabError",
    "ValidationError",
    "atr",
    "backtest",
    "backtest_async",
    "backtest_historical",
    "backtest_portfolio",
    "backtest_ticks",
    "benchmark_stats",
    "bps_of",
    "build_metrics",
    "cached_candles_path",
    "calculate_position_size",
    "candle_stats",
    "clamp_finite",
    "create_research_store",
    "detect_fvg",
    "ema",
    "export_backtest_artifacts",
    "export_html_report",
    "export_metrics_json",
    "export_trades_csv",
    "fetch_historical",
    "fetch_latest_candle",
    "financing_cost",
    "funding_events",
    "get_historical_candles",
    "get_strategy",
    "grid",
    "in_windows_et",
    "is_session",
    "last_swing",
    "list_strategies",
    "load_candles_from_cache",
    "load_candles_from_csv",
    "merge_candles",
    "minutes_et",
    "normalize_candles",
    "offset_et",
    "optimize",
    "parse_windows_csv",
    "pct",
    "periods_per_year",
    "register_strategy",
    "render_html_report",
    "research",
    "save_candles_to_cache",
    "structure_state",
    "summarize",
    "swing_high",
    "swing_low",
    "to_primitive",
    "walk_forward_optimize",
    "with_budget",
]
