"""TradeLab's public Python API."""

from .data import (
    backtest_historical,
    cached_candles_path,
    candle_stats,
    fetch_historical,
    fetch_latest_candle,
    get_historical_candles,
    load_candles_from_cache,
    load_candles_from_csv,
    merge_candles,
    normalize_candles,
    save_candles_to_cache,
)
from .engine import (
    BarSystemRunner,
    BudgetExceededError,
    LlmSignal,
    backtest,
    backtest_async,
    backtest_portfolio,
    backtest_ticks,
    financing_cost,
    funding_events,
    grid,
    optimize,
    walk_forward_optimize,
    with_budget,
)
from .errors import (
    BrokerError,
    DataProviderError,
    LiveTradingDisabledError,
    RiskRejectedError,
    StrategyError,
    TradeLabError,
    ValidationError,
)
from .models import BacktestResult, Candle, Signal, to_primitive
from .strategies import get_strategy, list_strategies, register_strategy

__all__ = [
    "BacktestResult",
    "BarSystemRunner",
    "BrokerError",
    "BudgetExceededError",
    "Candle",
    "DataProviderError",
    "LiveTradingDisabledError",
    "LlmSignal",
    "RiskRejectedError",
    "Signal",
    "StrategyError",
    "TradeLabError",
    "ValidationError",
    "backtest",
    "backtest_async",
    "backtest_historical",
    "backtest_portfolio",
    "backtest_ticks",
    "cached_candles_path",
    "candle_stats",
    "fetch_historical",
    "fetch_latest_candle",
    "financing_cost",
    "funding_events",
    "get_historical_candles",
    "get_strategy",
    "grid",
    "list_strategies",
    "load_candles_from_cache",
    "load_candles_from_csv",
    "merge_candles",
    "normalize_candles",
    "optimize",
    "register_strategy",
    "save_candles_to_cache",
    "to_primitive",
    "walk_forward_optimize",
    "with_budget",
]
